name: test

on:
  push:
    branches:
      - '**'
      - '!main'

env:
  GO_VERSION: '1.16'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/go/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v3
      - run: cd GetNewApp && go test ./... -v --cover
